spring.application.name=backend-java
server.port=8081

# Database Config (MySQL op Oege)
spring.datasource.url=jdbc:mysql://oege.ie.hva.nl:3306/zahmadm9
spring.datasource.username=ahmadm9
spring.datasource.password=U7sHFvxC8we0k/ag
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Frontend URL (for CORS)
election.frontend.url=http://localhost:5173

# A long, random, and secret string for signing JWTs.
jwt.secret=MijnGeheimeTokenSleutelVoorHetVerkiezingProject1234

# E-MAIL INSTELLINGEN
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bedrijfmelvin88@gmail.com
spring.mail.password=nwrfcjclbjjponop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

